### ISSUE TITLE
_underscore as variable name prefix

### ISSUE THREAD

**Issue by icy** [icy/bash-coding-style#10]
Though it's part of my coding style, sometimes I see it's very annoying. Yes I admit that :P in some long script I strictly follow the convention, but I also often break the rule. 

https://github.com/icy/bash-coding-style#variable-names

Is that good to deprecate that one?

cc: @cuonglm @cmpitg (well, I hope you still have some .bash somewhere on your laptop :D)

**Comment by cuonglm** [comment]
For me, it's a :+1: for deprecating this one.

The main purpose as describe in the style guide can be archived with `${this_is_a_variable}`. That feels more natural and iconsistent with other guide like Google.

The only software that I notice so far, which use `_` in variable name is https://developer.apple.com/library/archive/technotes/tn2228/_index.html#//apple_ref/doc/uid/DTS40007991-CH1-SUBSECTION15

**Comment by icy** [comment]
Thanks @cuonglm. Let me fix that. My new script would follow new style and I don't think I need to rewrite all past scripts.  

Btw, there is some bash formatter :D

**Comment by icy** [comment]
I have a (tough) chance to look at some of my code I wrote 18 years ago. Now I know where my `_` comes from. It's inspired by Python coding style https://docs.python.org/2/library/inspect.html =))

**Comment by icy** [comment]
> I have a (tough) chance to look at some of my code I wrote 18 years ago. Now I know where my `_` comes from. It's inspired by Python coding style https://docs.python.org/2/library/inspect.html =))

I learnt Python before I learnt Bash :D
