### ISSUE TITLE
functions names just curious

### ISSUE THREAD

**Issue by skironDotNet** [icy/bash-coding-style#6]
why camel is bad? underscores are mess

thisIsBeautifulName

this_is_ugly_slow_to_type_name

ideally-i-would-do-this-but-not-sure-if-legal

:)

**Comment by icy** [comment]
Thanks @skironDotNet . I haven't known about your comment (I turned off github notification completely somehow :D). I have fixed in the latest commit. Hope that's better now.

Best,

**Comment by icy** [comment]
and see also #1
