### ISSUE TITLE
[Question] What about arrays?

### ISSUE THREAD

**Issue by cristoferfb** [icy/bash-coding-style#7]
Hi, Arrays (or data structures) will have the same name convention than normal variables? I am thinking about plural names or something alike.

**Comment by icy** [comment]
Hi @cristoferfb , that's very good question. I like your idea.

Bash doesn't even care much (check it out with LINENO and FUNCNAME: https://github.com/icy/bash-coding-style#a-little-tracing ).

In my works, I am trying to avoid array / associate arrays if possible; if I have to use them, I just use the normal variable names. I meant, I don't add any special meaning to the variable name. I'm not really sure how the new convention would help much.

What do you think @cuonglm ? Let's discuss if a few people can agree on a new convetion we can move on.

Thanks a lot.

**Comment by cuonglm** [comment]
Bash or shell in general is not a strong type language, so it depends on your team to have its own naming convention.

**Comment by cristoferfb** [comment]
@cuonglm I found this repo searching code style and naming conventions, the _ for inner variables is useful I think the plural in array or maps give more semantic to all the code precisely for it weak type.

**Comment by icy** [comment]
You both have good idea. And because there can't be a single rule that fits in all cases, I would go with a simple section in the style that can help to explain `what is not my style`. Stay tuned, and thanks

**Comment by icy** [comment]
I have added something in https://github.com/icy/bash-coding-style/pull/8/files . Thanks

**Comment by icy** [comment]
Thanks @cuonglm for your approval. Just a friendly request: I have invited you as the admin of the repo. I have been starting to have fail-over ownership for (all of) my projects, and I believe you can help a lot for this coding style project. Many thanks ^.^

**Comment by cuonglm** [comment]
> Thanks @cuonglm for your approval. Just a friendly request: I have invited you as the admin of the repo. I have been starting to have fail-over ownership for (all of) my projects, and I believe you can help a lot for this coding style project. Many thanks ^.^

I accepted.

**Comment by icy** [comment]
thx again, @cuonglm . I don't really know how access level works in personal github account; if you have any problems pls let me know.
